version: '3.4'

services:
  anibot:
    container_name: Anibot
    image: anibot
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000