version: '3.4'
services:
  anibot:
    image: anibot
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: ["nodemon", "--inspect=0.0.0.0:9229", "Anibot.js"]
