version: '3.4'
services:
  anibot:
    container_name: Anibot
    image: discord_bots
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000